import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next WorkOS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/sso">
        <h1>SSO &rarr;</h1>
      </Link>
      <Link href="/">
        <h1>Admin Portal &rarr;</h1>
      </Link>
      <Link href="/">
        <h1>Dyrectory Sync &rarr;</h1>
      </Link>
      <Link href="/">
        <h1>Magic Link &rarr;</h1>
      </Link>
    </div>
  )
}
